apiVersion: v1
kind: ServiceAccount
metadata:
  name: capi
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxx
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: capi
subjects:
- kind: ServiceAccount
  name: capi
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
    name: eksutils-pod
    labels: 
      app: toolbox
spec:
  containers:
  - name: eksutils
    image: allamand/eksutils:latest
    command:
      - tail
      - -f
      - /dev/null
#  - env:
#    - name: WORDPRESS_DATABASE_PASSWORD
#      valueFrom:
#        secretKeyRef:
#          key: mariadb-password
#          name: wordpress-rds-externaldb
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
#    volumeMounts:
#    - mountPath: /bitnami/wordpress
#      name: wordpress-data
#      subPath: wordpress
#      readOnly: true
  enableServiceLinks: true
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
  serviceAccount: default
  serviceAccountName: capi
#  volumes:
#  - name: wordpress-data
#    persistentVolumeClaim:
#      claimName: wordpress-rds
