# To generate this file you can execute commented lines below.
#POLICY_ARN=$(aws iam list-policies --query 'Policies[?PolicyName==`AdministratorAccess`].[Arn]' --output text)
#CLUSTER_NAME=eksworkshop-eksctl
#eksctl create iamserviceaccount \
#    --name eksutils-admin \
#    --namespace default \
#    --cluster $CLUSTER_NAME \
#    --attach-policy-arn $POLICY_ARN \
#    --approve \
#    --override-existing-serviceaccounts
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account_id>:role/<Role_Name>
  name: eksutils-admin
  namespace: default
